version: "3.7"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-cliente-frontend
    volumes:
      - ".:/home/node/app"
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "4200:4200"
      - "9229:9229"
    environment:
      - NODE_ENV=development
