version: '3.7'
services:

  backend:
    build:
      context: .docker/backend
      dockerfile: Dockerfile
    container_name: admin-cliente-backend
    entrypoint: >-
      dockerize -template ./.docker/backend/.env:./backend/.env -wait
      tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=sistema
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
      - _SALT=EGRNILIWmVWf2UyENHT8WBcV4FLTXSW6
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
      - '35729:35729'
    volumes:
      - '.:/var/www'
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: ./.docker/nginx
    container_name: admin-cliente-nginx
    restart: always
    tty: true
    ports:
      - '8000:80'
    volumes:
      - '.:/var/www'
    networks:
      - app-network
    depends_on:
      - backend

  db:
    container_name: db
    image: docker_db
    build:
      context: .docker/mysql
      dockerfile: Dockerfile
    hostname: db
    restart: always
    tty: true
    expose:
      - '33006'
      - '3306'
    ports:
      - '33006:3306'
      - '3306:3306'
    volumes:
      - './.docker/dbdata:/var/lib/mysql'
      - './.docker/mysql:/docker-entrypoint-initdb.d'
    command: --default-authentication-plugin=mysql_native_password
    # command: '--innodb-use-native-aio=0'
    environment:
      - MYSQL_DATABASE=sistema
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
